title: KAU Conference Deadlines # (Maintained by @mossr)
description: Deadline countdowns for conferences relating to research at the <a href='https://atmcl.kau.ac.kr/'>Air Transportation Modeling and Control Laboratory (ATMCL)</a>
author: Seokbin Yoon (forked from Abhishek Das and Robert Moss)

domain: "atmcl.github.io"
baseurl: "/KAU-deadlines"

twitter_username: none
twitter_hashtag: none
github_username: seokbinyoon96
github_repo: KAU-deadlines

github: [metadata]

repository: seokbinyoon96/KAU-deadlines

markdown: kramdown
ga_id: 

include: ['_pages']
